
const STATUS_CODES={
    NOT_FOUND:404,
    ARGS_ERROR:50,
    ERROR_DATA:100,
    ERROR_AUTENTICACION:401,
    ERROR_AUTH:403
}

const ERRORES_INTERNOS={
    ARGUMENTOS:50,
    PERMISOS:2,
    OTROS:500
}

module.exports={STATUS_CODES,ERRORES_INTERNOS}